Fast checking command
lidofinance/lido-node-operator-key-checker-cli pull request #6
Opened 2021-08-03 15:23 UTC by avsetsin

2021-08-04 14:44 UTC, kolyasapphire requested changes
Also needs `packages` modifications in `pyproject.toml`, probably:
```
[
	{ include = "*.py" },
]
```
This is needed for proper packaging of all needed modules in the final package.

2021-08-05 12:05 UTC, avsetsin commented on README.md
> +--rpc						RPC provider for network calls.
I replaced tabs in the whole block with spaces. So, now it works the same everywhere

2021-08-05 12:07 UTC, avsetsin commented on README.md
> +lido-cli --rpc https://mainnet.provider.io/v3/XXX --clear_cache=False validate_network_keys_fast
Yes, you are right. I added the extra example

2021-08-05 12:24 UTC, kolyasapphire approved these changes

2021-08-05 12:27 UTC, ujenjt approved these changes
LGTM

2021-08-05 12:35 UTC, merged